# Generated by Django 6.1 on 2026-08-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="last_reminder_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата последнего напоминания"
            ),
        ),
    ]
